#端口
server.port=8397

# 开启文件上传
spring.servlet.multipart.enabled=true
# 文件写入磁盘的阈值
spring.servlet.multipart.file-size-threshold=2KB
# 最大文件大小
spring.servlet.multipart.max-file-size=100MB
# 最大请求大小
spring.servlet.multipart.max-request-size=300MB

# 文件存储参数
# file.upload-dir=./files
